### ISSUE TITLE
ijm-00105.xml aff institutions

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#100]
When I convert the `ijm-00105.xml` file to JSON output, there are validation errors due to the author affiliations do not have an institution name.

Looking at the XML file, I see institutions, like these:

```
<institution content-type="institution">
Max Planck Institute for Demographic Research Rostock
</institution>
...
<institution content-type="institution">
Leibniz Institute for Educational Trajectories Bamberg
</institution>
```

Due to how our conversion process works right now, the `content-type="institution"` is not an attribute recognised yet.

I will assign this to you please @Melissa37, because I'm not entirely sure whether the above tagging is desired. It is not the same as in the other XML files, however, and it will not show on the demo site without either XML content changes or parsing code changes.

**Comment by Melissa37** [comment]
@gnott Thanks, it's not, we just have `<institution>`

However, I think we require a city too (currently we ask for this like this: 
```
<addr-line>
                                        <named-content content-type="city">Cambridge</named-content>
</addr-line>
```

But in future will change that to `<city>`).

@Vijayarajmurugesan please correct the institution tagging only.

Thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
