### ISSUE TITLE
ijm-00115.xml appendix

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#101]
I found an issue in validating JSON produced from `ijm-00115.xml` related to the appendix content. After a little poking around, I have found if I change:

```
<app-group>
<title>Appendices</title>
<app id="app">
```

to

```
<app-group>
<app id="app">
<title>Appendices</title>
```

then the mandatory `title` attribute for the appendix is populated.

I think this order of tagging is used already in some previous IJM appendix content.

@Vijayarajmurugesan if you agree and you can move the title tag in the appendix section, please do it and resupply it? Thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott I have fixed the above issue and resupplied the package to the below ftp site:

https://exeterpremedia.exavault.com/share/view/1jm6r-6kjkpwlw

Regards,
Vijay

**Comment by gnott** [comment]
The latest package produces valid output, thanks again @Vijayarajmurugesan.
