### ISSUE TITLE
ijm-00117.xml boxed-text sec tags

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#102]
I found a validation error for article `00117` related to the boxed text content. I think I tracked it down to the `<sec>` tags inside the `<boxed-text>` tags, e.g. 

```
<boxed-text id="box1">
<sec id="b1">
<label>Box 1.</label>
...
```

I haven't found many examples of `<boxed-text>` in the IJM content to compare to, so I'm asking for some input from you please @Melissa37.

When I remove the `<sec>` tags from the `<boxed-text>`, then it produces valid JSON output.

Do we need the `<sec>` tags here?

**Comment by Melissa37** [comment]
@gnott I agree with you, no need for the `<sec>`tag here.

@Vijayarajmurugesan please can you resupply

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
