### ISSUE TITLE
ijm-00119.xml

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#103]
Similar to issue https://github.com/microsimulation/ijm-xml/issues/100, the JSON output is invalid due to the author aff is missing an institution name. The XML in this case has:

```
<institution content-type="institute">
```

Can / should this tag be changed to `<institution>`?

**Comment by Melissa37** [comment]
Same response as for  #100
@Vijayarajmurugesan please can you resupply

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
