### ISSUE TITLE
Article 00120

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#104]
I think the `ijm-00120-vor-r1.zip` supplied may be incomplete or corrupt? I am getting some warnings and my scripts are not finishing the processing of the zip as it has for others.

I notice as well in the XML, the file names for figures have `ijm.00120` style naming, with a `.` dot instead of `-` hyphen in the names. I don't think this is related to the zip file integrity, but I thought I'd mention it now for inclusion in a possible resupply.

@Vijayarajmurugesan could you please check on the `<graphic>` XML tag file name values, and resupply the zip file? Thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott I have fixed the above issue and resupplied the package to the below ftp site:

https://exeterpremedia.exavault.com/share/view/1jm6r-6kjkpwlw

Regards,
Vijay

**Comment by gnott** [comment]
Thanks for changing the names on the files @Vijayarajmurugesan, I can produce valid output now.

I notice an interesting file name, `ijm-00120-math18.tif`. I don't think eLife articles uses `-math` in any of our file names, so I thought I'd mention to @Melissa37 in case this is worthy of additional comment.
