### ISSUE TITLE
ijm-00124.xml display-channel

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#105]
I am requesting a small change to article `00124` please,

```
<subj-group subj-group-type="display-channel">
<subject>Book Review</subject>
</subj-group>
```

Would you please change the `R` to lower case, to

```
<subject>Book review</subject>
```

This will populate the article type value correctly.

Thanks @Vijayarajmurugesan!

**Comment by Vijayarajmurugesan** [comment]
@gnott I have fixed the above issue and resupplied the package to the below ftp site:

https://exeterpremedia.exavault.com/share/view/1jm6r-6kjkpwlw

Regards,
Vijay

**Comment by gnott** [comment]
Looks good, thanks @Vijayarajmurugesan!
