### ISSUE TITLE
ijm-00143.xml appendix and table

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#107]
A slightly tricky validation issue in article `00143`, I think I have a combination that produces a valid result.

Appendix part: the XML tagging is:

```
<app-group>
<app id="app1">
<sec id="A1">
<title>Annex</title>
```

It will become valid if a `<title>` tag is added to the `<app>` tag, I don't know what to put as a value though: To illustrate the position of the tag:

```
<app-group>
<app id="app1">
<title>A_TITLE_HERE</title>
<sec id="A1">
<title>Annex</title>
```

The other part is the first table in the appendix, `table3`, the `<table-wrap-foot>` content JSON output is not valid, until the `<fn>` tags are assigned an `id` attribute value. It seems to have a `label` you must also have an `id` on the table footnote (and to have an `id` you must have a `label`).

@Melissa37 I thought to run these suggestions by you first before specifying a resupply. Thanks!

**Comment by Melissa37** [comment]
Hi there

@Vijayarajmurugesan please can you remove the `<sec>` It's not needed and the XML validates against the DTD without it. @gnott not sure whether it will validate against the eLife schema, but if not then this has to go into the list of articles to be fixed on Libero.

Cheers!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
