### ISSUE TITLE
ijm-00144.xml list type and file names

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#108]
I have some requests for changes in the XML for article `00144` please:

```
<list list-type="bulllet">
```

Please change `"bulllet"` to `"bullet"`.

There are some figure file names in the XML with an `_` underscore instead of a `-` hyphen:

```
<graphic xlink:href="ijm-00144_fig1.tif" mimetype="image" mime-subtype="tiff"/>
...
<graphic xlink:href="ijm-00144_fig2.tif" mimetype="image" mime-subtype="tiff"/>
```

If you could please change these file names to have hyphens? Thanks @Vijayarajmurugesan!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
