### ISSUE TITLE
ijm-00145.xml file names and bib25

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#109]
Validating the output for article `00145`, there are couple parts for editing and resupply please:

File names in the XML have `_` instead of `-`:

```
<graphic xlink:href="ijm-00145_fig1.tif" mimetype="image" mime-subtype="tiff"/>
...
<graphic xlink:href="ijm-00145_fig2.tif" mimetype="image" mime-subtype="tiff"/>
```

If you would please replace the `_` with `-` in resupplied XML.

An issue in the reference with id `bib25`, it is fairly sparse for details. This is converted to the `unknown` type in JSON output we use, but it is invalid due to having no value to put into a `title`:

```
<ref id="bib25">
<element-citation publication-type="report">
<person-group person-group-type="author">
<collab>Commonwealth of Australia</collab>
</person-group>
<year iso-8601-date="2015">2015</year>
</element-citation>
</ref>
```

Is it possible you can add a value to use as a title for this reference? Based on other `"report"` references, it would be something to go into a `<source>` tag. If you cannot find a value yourself, could you please assign this back to Melissa for further investigation or enlisting others for content?

Thanks @Vijayarajmurugesan!

**Comment by gnott** [comment]
One more thing please, in

```
<app-group>
<app id="app1">
<label>A1.</label>
```

If you could please change the `<label>` tag to a `<title>` tag, then the appendix output will be valid

```
<app-group>
<app id="app1">
<title>A1.</title>
```

Thanks again!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
