### ISSUE TITLE
ijm-00160.xml author aff

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#110]
In the author affiliation for article `00160`, the JSON output is no valid without an institution name.

My suggestion for the change to the XML would be from:

```
<aff id="aff1"><label>1</label><addr-line>Independent Researcher</addr-line>
```

If you could please replace the `<addr-line>` tag with an `<institution>` tag, thus:

```
<aff id="aff1"><label>1</label><institution>Independent Researcher</institution>
```

I feel like this is probably an acceptable request regarding the structure of the XML, but I would also like to ping @Melissa37 to be aware of it in case it requires a little more finesse.

@Vijayarajmurugesan if you would please review this and consider to change and resupply, unless you would like to wait for comments from @Melissa37 first. Thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott Yes, your comment is valid. Now am fixed as you requested above. Ihave uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
