### ISSUE TITLE
ijm-00170.xml and ijm-00171.xml display channel and article type

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#112]
Validating XML for article `00170`, there are a couple values I've not seen in the IJM articles so far. One,

```
<article article-type="Software review" ...
```

Two, slightly further along:

```
<subj-group subj-group-type="display-channel">
<subject>Product-review</subject>
</subj-group>
```

I do not have a code rule to convert `"Product-review"` (although maybe this should be `"Product review"` in the end) to most likely the `scientific-correspondence` display channel, similar to how `"Book review"` is converted.

In the former example,`article-type`, I do not know whether `"Software review"` is the ideal final article type?

This sounds to me like something you could please consider and comment on @Melissa37 - thanks!

**Comment by gnott** [comment]
Adding `ijm-00171.xml` to the title of this issue, which also has the same values.

**Comment by Melissa37** [comment]
@Vijayarajmurugesan For Continuum and Libero I think we will stick to the suggested values for `@article-type` from JATS: https://jats.nlm.nih.gov/archiving/tag-library/1.2/attribute/article-type.html

Please convert to `product-review`

```
<subj-group subj-group-type="display-channel">
<subject>Product-review</subject>
</subj-group>
```
This should be Software review.

Please remember that the content in `<subject>` is displayed so I think it is unlikely IJM would display this term with a hyphen like this.

Please resupply.

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
