### ISSUE TITLE
ijm-00173.xml file name and confproc references

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#113]
Checking for validity on article `00173` output, I have some requests for changes please:

1. File name change

```
<graphic xlink:href="ijm.00173_fig1.tif" mimetype="image" mime-subtype="tiff"/>
```

If you would please change `"ijm.00173_fig1.tif"` to `"ijm-00173-fig1.tif"`.

2. References

Some references of type `"confproc"` do not produce a title in the JSON output. The id values of these references:

```
bib6
bib10
bib26
```

If you please change the `<source>` tags to `<article-title>` tags in these references then the output becomes valid. I looked quickly at the values and I think it is probably acceptable to say these are article titles?

@Vijayarajmurugesan if you would please consider these changes for a resupply? Thank-you!

**Comment by gnott** [comment]
Could you also please change the file name in

```
<self-uri content-type="pdf" xlink:href="ijm.00173.pdf"/>
```

to

```
<self-uri content-type="pdf" xlink:href="ijm-00173.pdf"/>
```

Thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
