### ISSUE TITLE
ijm-00174.xml file name, references, and app title

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#114]
Testing for validation of output from article `00174`, I identified some fairly simple changes when applied will result in valid output, which I think are suitable for resupply.

1. File name

In,

```
<graphic xlink:href="IJM_11_1_2_fig1.tif" mimetype="image" mime-subtype="tiff"/>
```

Would you please change the file name to `"ijm-00174-fig1.tif"`.

2. References of type `confproc`

The references of id

```
bib21
bib38
```

These will convert to valid output if the `<source>` tags are changed to `<article-title>` tags, if you would consider changing these please.

3. Appendix title

In the appendix, if you could change the tag order from:

```
<app-group>
<title>Appendix</title>
<app id="app">
```

to 

```
<app-group>
<app id="app">
<title>Appendix</title>
```

This will allow the required title to be added to the output.

Thanks for reviewing these and producing resupplied files @Vijayarajmurugesan!

**Comment by gnott** [comment]
Also regarding file names

4. PDF file name

Would you please change the file name

```
<self-uri content-type="pdf" xlink:href="ijm.00174.pdf"/>
```

to 

```
<self-uri content-type="pdf" xlink:href="ijm-00174.pdf"/>
```

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
