### ISSUE TITLE
ijm-00176.xml self-uri and confproc reference

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#116]
I am requesting some small changes to the XML for article `00176` please:

1. self-uri PDF

Would you please change the file name in

```
<self-uri content-type="pdf" xlink:href="ijm.00176.pdf"/>
```

to

```
<self-uri content-type="pdf" xlink:href="ijm-00176.pdf"/>
```

2. `bib45` changes

If you would please change the `<source>` tag to an `<article-title>` tag then the output will be valid on my side. I also noticed by chance the word `rplicate` in the title, that may instead be better as `replicate`?

Thanks @Vijayarajmurugesan!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
