### ISSUE TITLE
ijm-00178.xml file name changes

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#117]
Would you please make some changes in the XML for article `00178`,

1. self-uri

Please change

```
<self-uri content-type="pdf" xlink:href="ijm.00178.pdf"/>
```

to

```
<self-uri content-type="pdf" xlink:href="ijm-00178.pdf"/>
```

2. Figure name XML and figure files

In the XML would you please change

```
<graphic xlink:href="ijm.00178_fig1.tif" mimetype="image" mime-subtype="tiff"/>
...
<graphic xlink:href="Iijm.00178_fig2.tif" mimetype="image" mime-subtype="tiff"/>
```

To 

```
<graphic xlink:href="ijm-00178-fig1.tif" mimetype="image" mime-subtype="tiff"/>
...
<graphic xlink:href="ijm-00178-fig2.tif" mimetype="image" mime-subtype="tiff"/>
```

In the zip file, I think the tif file names have an `_` underscore instead of a `-` as well. Would you please rename the files `ijm-00178_fig1.tif` and `ijm-00178_fig1.tif` to `ijm-00178-fig1.tif` and `ijm-00178-fig1.tif`.

Thank-you @Vijayarajmurugesan!

**Comment by gnott** [comment]
Edited slightly the file name values on this issue, if you would please use the Github version and ignore the first version if you received it by email.

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
