### ISSUE TITLE
ijm-00183.xml figure file names

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#120]
There are two figure file names in the XML for `00183` to be updated please:

```
<graphic xlink:href="ijm.00183-fig1.tif" mimetype="image" mime-subtype="tiff"/>
<graphic xlink:href="ijm.00183-fig2.tif" mimetype="image" mime-subtype="tiff"/>
```

If you would please change the `ijm.` to `ijm-` to match the file names.

Thanks @Vijayarajmurugesan!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
