### ISSUE TITLE
ijm-00195.xml file name change

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#123]
One figure file name to change in the XML for article `00195` please, from

```
<graphic xlink:href="ijm.00194-fig1.tif" mimetype="image" mime-subtype="tiff"/>
```

to 

```
<graphic xlink:href="ijm-00195-fig1.tif" mimetype="image" mime-subtype="tiff"/>
```

This will match the file name in the zip package (also to the correct `00195` article id)

Thank-you @Vijayarajmurugesan!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
