### ISSUE TITLE
ijm-00142.xml bib18 XML

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#125]
I ran into an error due to malformed XML in article `00142`, specifically in reference `bib18`:

```
<ref id="bib18">
...
<source>Safeguarding social equity during fiscal consolidation: 
which tax bases to use? The role of tax policy in times of fiscal 
consolidation</article-title>
```

The `<source>` open tag here I think could be changed to an `<article-title>` open tag to match the close tag.

@Vijayarajmurugesan would you please review this and consider to resupply - thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
