### ISSUE TITLE
ijm-00171.xml malformed XML

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#126]
I have an error due to malformed XML in article `00171`, in the `<title-group>`

```
<article-title>The code <italic>and</italic> the model: A response to &#x201C;The code is the model&#x201D;, by Luzius Meisser</subtitle>
```

If you please change the `</subtitle>` close tag to an `</article-title>` close tag it will repair the malformed XML.

Thanks @Vijayarajmurugesan!

Please note there is also an issue for Melissa to review about article `00171` regarding the display channel and article type (https://github.com/microsimulation/ijm-xml/issues/112).

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
