### ISSUE TITLE
ijm-00172.xml self-uri

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#127]
I am looking specifically for `<self-uri>` values to compare.

In article `00172` XML would you please change

```
<self-uri content-type="pdf" xlink:href="ijm.00172.pdf"/>
```

to

```
<self-uri content-type="pdf" xlink:href="ijm-00172.pdf"/>
```

Thanks @Vijayarajmurugesan!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
