### ISSUE TITLE
ijm-00177.xml self-uri value

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#128]
In article `00177` XML would you please change

```
<self-uri content-type="pdf" xlink:href="ijm.00177.pdf"/>
```

to

```
<self-uri content-type="pdf" xlink:href="ijm-00177.pdf"/>
```

Thank-you @Vijayarajmurugesan!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
