### ISSUE TITLE
ijm 00167 package and XML changes

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#129]
I left this article for last in the batch of new articles sent (thankfully I think a first pass of validating is done on those - hooray!).

I ignored this for a little while because one of the figure files was causing a `500` error in the IIIF image server and I didn't want to slow down on checking the other files first.

Result of more in-depth checking of the `ijm-00167-fig2.tif` file for possible errors, although it displays in the OS as a thumbnail, I was unable to open it in Photoshop, where I intended to try resaving it which sometimes helps. Next, I opened it in a text editor, and the first line it looked like it is actually a `JPG` file.

1. Resave `ijm-00167-fig2.tif`

Could you please resave the `ijm-00167-fig2.tif` file as a `TIF` format and include that in the resupplied zip package?

Changing the file name on my system allowed me to continue with XML validation

2. List types

There are two of these tags

```
<list list-type="lower-alpha">
```

Would you please change the two to

```
<list list-type="alpha-lower">
```

The validation rules I have check for these values. I believe `"alpha-lower"` is the recommended type for JATS (whereas `"lower-alpha"` is possibly the one used in HTML).

3. Reference `bib13`

In `bib13` of type `confproc`, would you please change

`<source>The social and budgetary impacts of recent social security reform in Belgium</source>`

to

`<article-title>The social and budgetary impacts of recent social security reform in Belgium</article-title>`

This will populate the reference title that the demo site requires.

Thanks @Vijayarajmurugesan!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay

**Comment by gnott** [comment]
Thank-you @Vijayarajmurugesan - I have been able to generate output for all the resupplied articles (with some changes, in new issues). I will go through and close all the resupply column issues with no additional comments to save time, so a big thanks for sending them all through!
