### ISSUE TITLE
ijm-00159.xml author aff institutions

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#130]
In a round of regenerating content for inclusion in the demo site, I have run into a validation error on author institutions in article `00159`. The solution would be similar to issue https://github.com/microsimulation/ijm-xml/issues/100, using only `<institution>` tags.

The affiliation values in the XML for potential editing and resupply:

```
<aff id="aff1">
<institution content-type="dept">GeoHealth Laboratory, University of Canterbury</institution>
<country>New Zealand</country>
</aff>
<aff id="aff2">
<institution content-type="institution">Carinthia University of Applied Sciences</institution>
<country>Austria</country>
</aff>
<aff id="aff3">
<institution content-type="institution">Galileo University</institution>
<country>Guatemala</country>
</aff>
```

I suggest changing any `<institution content-type="dept">` or `<institution content-type="institution">` to just an `<institution>` tag. It will populate the required property for the demo site to show the article.

@Vijayarajmurugesan would you please take a look at this for a possibly resupply - thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
