### ISSUE TITLE
ijm-00145.xml bib4 bib9

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#134]
Checking the resupplied content (thanks @Vijayarajmurugesan!), in the resupplied XML for `00145` there are a couple references of type `"report"` with `<article-title>` instead of `<source>` tags:

```
bib4
bib9
```

@Vijayarajmurugesan could you please update your copies of these? No real need to resupply if you do this, because I'm going to use my altered XML to generate valid output for the demo site. Thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott I have fixed this issue and uploaded to the below ftp site:
https://exeterpremedia.exavault.com/share/view/1jp35-83pn2y54

Thanks,
Vijay

**Comment by gnott** [comment]
Thanks @Vijayarajmurugesan the file you supplied is now valid for the demo site.
