### ISSUE TITLE
ijm-00174.xml bib141 and bib160

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#135]
To produce valid output for the demo site, I have lightly edited my copy of article `00174` XML. There are two references with some extra data:

bib141

`<string-name></string-name>`

This produces an author record with a blank surname and first name, which is invalid in the demo site. I have remove this tag from my XML

bib160 

`<string-name></string-name><collab>P</collab>`

Here also the blank `<string-name>` is causing problems. The `<collab>` tag here I think may be out of place and will probably not end up in the demo site, however is might be a problem in Libero later.

@Vijayarajmurugesan if you would please update your copy of this article for future support - thanks! Also please check with @Melissa37 or others about the `<collab>` tag if you want.

**Comment by Vijayarajmurugesan** [comment]
@gnott Sorry for the issue caused. Now am fixed the issue and uploaded to the below ftp site:
https://exeterpremedia.exavault.com/share/view/1jp35-83pn2y54

Thanks,
Vijay

**Comment by gnott** [comment]
Thanks again @Vijayarajmurugesan, this article is valid for the demo site too.
