### ISSUE TITLE
Article pub date changes

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#136]
I am adding the remaining articles to demo site volume / issues, and it is easy to spot some article pub dates that may need to be updated.

I don't think these need a "resupply" at this stage (I'm unsure of the need to send it to me at this stage), but would you please consider to change the copy you have so the pub dates are correct going forward?

`00117` please change to Aug 31, 2015
`00155` please change to Aug 31, 2017
`00161` please change to Aug 31, 2017
`00162` please change to Aug 31, 2017
`00192` please change to Apr 30, 2019

These are based on the issue I put the articles into, I hope these suggested dates are correct. Please check if the dates or volume / issue is correct, or I my suggested dates are wrong - thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott Yes, your mentioned date is correct. I have fixed this issue and uploaded to the below ftp site:
https://exeterpremedia.exavault.com/share/view/1jp35-83pn2y54

Thanks,
Vijay

**Comment by gnott** [comment]
The resupplied XML looks good, thanks @Vijayarajmurugesan! I will be updating the demo site with these shortly.
