### ISSUE TITLE
ijm-00187.xml table-wrap-group

### ISSUE THREAD

**Issue by FAtherden-eLife** [microsimulation/ijm-xml#141]
In the latest ijm-00187.xml file, `table-wrap-group` has been used to capture two tables with the same overall label/title.

The label and title have been captured as a child of the first `table-wrap` (not the group):
```xml
<table-wrap-group>
    <table-wrap id="tableb1" position="float">
        <label>Table B.1.</label>
        <caption>
            <title>Parameter estimates of the expenditure share equations.</title>
        </caption>
        <table frame="hsides" rules="groups">
            ...
        </table>
    </table-wrap>
    <table-wrap position="float">
        ...
    </table-wrap>
</table-wrap-group>
```

I think this would be best captured using one `table-wrap` containing two `table` elements, since (my understanding is) `table-wrap-group` is intended as a grouping of numerous tables each with their own labels/captions (and this is not the case for this content).
```xml
<table-wrap id="tableb1" position="float">
    <label>Table B.1.</label>
    <caption>
        <title>Parameter estimates of the expenditure share equations.</title>
    </caption>
    <table frame="hsides" rules="groups">
         ... 
    </table>
    <table> 
         ... 
    </table>
</table-wrap>
```

However if `table-wrap-group` is preferred,  then the label/title should be moved up as a child of `table-wrap-group` since it's applicable to both objects (I suspect the `@id` should also be on the `table-wrap-group` instead):

```xml
<table-wrap-group id="tableb1">
    <label>Table B.1.</label>
    <caption>
        <title>Parameter estimates of the expenditure share equations.</title>
    </caption>
    <table-wrap position="float">
        <table frame="hsides" rules="groups">
            ...
        </table>
    </table-wrap>
    <table-wrap position="float">
        ...
    </table-wrap>
</table-wrap-group>
```

**Comment by Vijayarajmurugesan** [comment]
@FAtherden-eLife  This is one fixed. I have uploaded the updated package to the below link:

https://exeterpremedia.exavault.com/share/view/1p0o7-84cs4vbg

Regards,
Vijay

**Comment by FAtherden-eLife** [comment]
Thanks
