### ISSUE TITLE
ijm-00002.xml page numbers

### ISSUE THREAD

**Issue by FAtherden-eLife** [microsimulation/ijm-xml#142]
In `ijm-00002.xml` page numbers are currently captured using `sec/title`. This means that the article will have strange nesting/TOC.

Suggest including them as roman or `bold` text in the appropriate `p` element (or other content container):
```xml
<p><bold>[116]</bold> Existing models of our socio-economic system have proved to be of rather ... </p>
```

An alternative would be to use processing-instructions:
```xml
<p><?page value-of="[116]"?> Existing models of our socio-economic system have proved to be of rather ... </p>
```

But there's no guarantee these would display in Libero, since this has not yet been discussed.

Another alternative would be `named-content`:
```xml
<p> ... [<named-content content-type="page-number">116</named-content>] ... </p>
```

**Comment by Melissa37** [comment]
@FAtherden-eLife do any open source publishers publish conference proceedings? I wonder whether we could look at that as a model for this?

**Comment by FAtherden-eLife** [comment]
> @FAtherden-eLife do any open source publishers publish conference proceedings? I wonder whether we could look at that as a model for this?

@Melissa37, yes, but I've only been able to find full text available as PDF. Outside of TEI (in which `pb` is used), I've mostly seen pages captured as processing instructions elsewhere.

As far as I'm aware, there's no prescriptive tag in JATS for in-text page numbers. Another alternative to throw into the mix would be something like:
```xml
<p> ... [<named-content content-type="page-number">116</named-content>] ... </p>
```

I'll add that into the ticket above.

**Comment by Melissa37** [comment]
@FAtherden-eLife I think your first suggestion would be the best approach to prevent working being done for a one-off archive article :-) But that's my opinion 

`<p><bold>[116]</bold> Existing models of our socio-economic system have proved to be of rather ... </p>`

Thanks!

**Comment by FAtherden-eLife** [comment]
> @FAtherden-eLife I think your first suggestion would be the best approach to prevent working being done for a one-off archive article :-) But that's my opinion

Sounds good - thanks! I can't add this ticket to the 'Resupply required' column in the project (presumably due to permissions), so would appreciate if you could do that for me!

**Comment by Melissa37** [comment]
Done! That's weird, we should look at that tomorrow

**Comment by FAtherden-eLife** [comment]
Thanks!
