### ISSUE TITLE
Arrays in ijm-00105.xml

### ISSUE THREAD

**Issue by FAtherden-eLife** [microsimulation/ijm-xml#143]
`ijm-00105.xml` contains two arrays - for example:
```xml
<array>
<tbody>
<tr>
<th>ID</th>
<th>birthDate</th>
<th>Tstart</th>
<th>Tstop</th>
<th>status Entry</th>
<th>status Exit</th>
<th>OD</th>
<th>ns</th>
<th>Epi sode</th>
<th>sex</th>
<th>fert</th>
<th>marital</th>
<th>edu</th>
</tr>

<tr>
<td>1</td>
...
</tbody>
</array>
```

This is valid capture, but _eLife_ would capture this as an 'inline' table. Should this be changed?

Also, it looks like the content should have `monospace` formatting, which doesn't seem to be present:
<img width="622" alt="Screen Shot 2019-08-08 at 09 16 27" src="https://user-images.githubusercontent.com/43879983/62686859-78505980-b9bd-11e9-9f32-77f519107485.png">

**Comment by Melissa37** [comment]
@FAtherden-eLife as discussed:

monospace formatting in PDF so Exeter to add this tagging to the XML

eLife to support array even if converted to table on front end

Can you create a new ticket for Exeter's instructions to go in the Resupply required column.

Thanks!

**Comment by FAtherden-eLife** [comment]
Thanks, raising separate ticket for missing Monospace formatting.
