### ISSUE TITLE
Missing Monospace formatting in ijm-00105.xml

### ISSUE THREAD

**Issue by FAtherden-eLife** [microsimulation/ijm-xml#144]
`ijm-00105.xml` has two arrays. The data within both of these should have monospace formatting but in both cases this is missing. For example:
```xml
<array>
<tbody>
<tr>
<th>ID</th>
<th>birthDate</th>
<th>Tstart</th>
<th>Tstop</th>
<th>status Entry</th>
<th>status Exit</th>
<th>OD</th>
<th>ns</th>
<th>Epi sode</th>
<th>sex</th>
<th>fert</th>
<th>marital</th>
<th>edu</th>
</tr>

<tr>
<td>1</td>
...
</tbody>
</array>
```
PDF for reference:
<img width="622" alt="pdf" src="https://user-images.githubusercontent.com/43879983/62695396-2b28b380-b9ce-11e9-845b-55ba6c203694.png">

**Comment by FAtherden-eLife** [comment]
@Melissa37 please can you add this to the Resupply required column? Thanks!

**Comment by Vijayarajmurugesan** [comment]
@FAtherden-eLife This is one fixed. I have uploaded the updated package to the below link:

https://exeterpremedia.exavault.com/share/view/1p0o7-84cs4vbg

Regards,
Vijay

**Comment by FAtherden-eLife** [comment]
Thanks
