### ISSUE TITLE
article-type attribute in ijm-00168.xml

### ISSUE THREAD

**Issue by FAtherden-eLife** [microsimulation/ijm-xml#147]
`article/@article-type` in this article is incorrect:
```xml
<article xmlns:ali="http://www.niso.org/schemas/ali/1.0/" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink" 
article-type="research article" 
dtd-version="1.2">
```

It needs changing from `research article` to `research-article`.

**Comment by Vijayarajmurugesan** [comment]
This is one fixed. I have uploaded the updated package to the below link:

https://exeterpremedia.exavault.com/share/view/1p0o7-84cs4vbg

Regards,
Vijay

**Comment by FAtherden-eLife** [comment]
Thanks!
