### ISSUE TITLE
Corrections to Subjects/Research Categories

### ISSUE THREAD

**Issue by FAtherden-eLife** [microsimulation/ijm-xml#151]
The following IJM articles have incorrect subjects/Research Categories (i.e. the content of this element - `//*:article//*:article-categories//*:subj-group[@subj-group-type="heading"]/*:subject`):

- **ijm-00187.xml**: change `consumption, savings and wealth` to  `Consumption, savings and wealth`.
- **ijm-00071.xml**: change `Micro-Macro linkage` to  `Micro-macro linkage`.
- **ijm-00046.xml**: change `Retirement` to  `Pensions and retirement`.

**Comment by Vijayarajmurugesan** [comment]
@FAtherden-eLife This is one fixed. I have uploaded the updated package to the below link:

https://exeterpremedia.exavault.com/share/view/1p0o7-84cs4vbg

Regards,
Vijay

**Comment by FAtherden-eLife** [comment]
Thanks
