### ISSUE TITLE
Topics have been updated

### ISSUE THREAD

**Issue by Melissa37** [microsimulation/ijm-xml#18]
![Screenshot 2019-04-18 at 21 26 51](https://user-images.githubusercontent.com/6051876/56389173-caa81780-6220-11e9-9f7a-141913f48aed.png)

Old: Social protection
New: Taxes and benefits

Old: Retirement
New: Pensions and retirement

Old: Small area estimation
New: Spatial microsimulation

Old: Savings and wealth
New: Consumption, savings and wealth

Brand new, no old version
New: Trade
New: Firm behaviour
New: Dynamic microsimulation

**Comment by gnott** [comment]
I have a branch with subjects changes, awaiting access rights to the https://github.com/microsimulation/demo project to add them in.

**Comment by gnott** [comment]
@Melissa37 I created a PR for changes to the subjects in the demo project, waiting for a review by others before merging.
