### ISSUE TITLE
IJM volume 1 pub date

### ISSUE THREAD

**Issue by Melissa37** [microsimulation/ijm-xml#22]
From @gnott 
The pub date in articles of 
IJM Volume 1, which is Autumn, in the XML is April 30, 2007. The pub 
date for articles 00001 to 00007 should be August 31, 2007, I think.

**Comment by Melissa37** [comment]
Reference:
https://docs.google.com/spreadsheets/d/1NVrM0u8mokZGrRa5aHr9YOfnL0jy0h49HyAaXzlUn_Y/edit#gid=0

Includes pub dates:
![Screenshot 2019-05-03 at 17 07 34](https://user-images.githubusercontent.com/6051876/57150349-f7823000-6dc5-11e9-8af2-fa7228e89cc4.png)

**Comment by Melissa37** [comment]
@Vijayarajmurugesan and @gnott I have pasted above the publication dates and linked to the spreadsheet.

I don't think either are right - vol 1 pub date is 31st DEC 2007.

This will need a resupply.

**Comment by gnott** [comment]
I am previewing content received so far, which I'm adding to the demo project. I created issues for the dates above for articles to be associated with.

Unfortunately, the issue dates do not match the article pub dates for all articles from `00001` to `00040`, inclusive. These may all need to be resupplied with new pub dates.

@Melissa37 if you could please confirm the dates I am seeing need correcting.

Articles `00041` to `00054` pub dates are correct!

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 

I have fixed it throughout the issues.

Thanks,
Vijay

**Comment by Melissa37** [comment]
Thanks!

**Comment by gnott** [comment]
Dates for volume 1 articles look ok when I checked a few, thanks @Vijayarajmurugesan! I can assume the dates will be correct for articles that are not resupplied yet (00020 to 00040 that may have had an incorrect date). I'll close this issue, and proofing on the web can spot any errors if they exist for pub dates.
