### ISSUE TITLE
QC on Continuum instance to check for other potential "eLife-ness" of the website

### ISSUE THREAD

**Issue by Melissa37** [microsimulation/ijm-xml#26]
@BlueReZZ @giorgiosironi 

I pushed some IJMicrosim data to this branch on the demo project: 
https://github.com/microsimulation/demo/tree/volume1 It includes some 
tweaks to display not-so-valid reference data.

Article 00005 is not valid yet, the dates on these first seven articles 
are not correct, and these will be changed in a subsequent supply from 
ExeterPremedia.

If you'd like to try getting the volume 1 branch running for a preview, 
please do! I'm sure Melissa would be interested to see it. It might be 
helpful to see if the volume 1 branch could be made visible on the 
Internet to allow others to review the site without learning how to run 
Docker.

It could be gathering feedback from eLife first might be an idea, for 
example where article say "CITE AS: eLife 2007;1:n/a" at the top (the 
n/a being a necessary elocation-id which is not in the XML), the meta 
tags has some eLife content as well. I also noticed the copyright dates 
are 2012 for 2007 articles, and I think those are tied into eLife's 
first year of publication. There must be others to find too, before 
showing it to IJM? Or leave it to them to review? Up to you!

Please let me know if I can help in the review process somehow. My next 
steps will be to further automate the content conversion I have going 
on, and convert more articles.

Todo

- [x] CITE AS updated
- [x] HTML `<title>` tag fixed
- [x] Copyright year fixed

**Comment by Melissa37** [comment]
@gnott please can you add the other things you've noticed to this ticket

**Comment by gnott** [comment]
Some eLife examples I've noticed:

1. `CITE AS` at the top of an article (as mentioned above). E.g. circled in red below

![image](https://user-images.githubusercontent.com/1779115/57340694-c7030480-70eb-11e9-9920-176d6748febd.png)

2. Title tag, e.g.

`<title>Editorial | eLife</title>`

(should be fairly simple, but if I could get exact wording please?)

3. Meta tags

A portion of the meta tags with some eLife-like content:

```

<meta name="dc.publisher" content="eLife Sciences Publications Limited">
...
<meta property="og:site_name" content="eLife">
<meta property="og:url" content="http://localhost:8080/articles/00001">
...
<meta name="twitter:site" content="@eLife">
```

4. Hidden page content

There are some eLife words mentioned in some hidden elements on the page. I can point these out, if they matter, they probably won't matter for the demo?

E.g.

`<span class="visuallyhidden" >eLife home page</span>`

5. Copyright year

The copyright year seems to be generated based on the volume value and the year eLife first published. Screenshot:

![image](https://user-images.githubusercontent.com/1779115/57340923-f49c7d80-70ec-11e9-8a3b-c63c906bebbc.png)

Presumably I should find this and change it.

**Comment by Melissa37** [comment]
@matteorichiardi can you let us know whether we should use International Journal of Microsimulation or IJM in the Cite as line?

Thanks!

**Comment by Melissa37** [comment]
>Meta tags
>hidden page content

@matteorichiardi can you confirm that for the purposes of the demo this is OK to leave with eLife name and not IJM?

**Comment by Melissa37** [comment]
@gnott 
>Copyright year

Yes please!

**Comment by matteorichiardi** [comment]
International Journal of Microsimulation

thanks. Matteo

**Comment by gnott** [comment]
Copyright year fixed in https://github.com/microsimulation/demo/pull/8.

**Comment by gnott** [comment]
Going with `CITE AS: IJM 2007;1:n/a` - with a simple string replacement.

**Comment by gnott** [comment]
Changing `<title>` tag in https://github.com/microsimulation/demo/blob/master/journal/app/Resources/views/base.html.twig

**Comment by gnott** [comment]
Committing eLife-ness changes in https://github.com/microsimulation/demo/pull/9

This should cover all the basics now, if someone would please confirm whether we should leave this open to collect additional feedback?

**Comment by Melissa37** [comment]
@gnott I think we can close this ticket and open new one(s) as we find further issues.

Thanks!
M
