### ISSUE TITLE
ijm-00114.xml content and validation

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#27]
Converted `ijm-00114.xml` as a test, there are some issues

1. Validation issue
`bib15` is type `<element-citation publication-type="working-paper">`, currently the demo site does not support `working-paper` types, having no template on how to display it. If it is possible please to change this to one of the reference types already supported? If not, I may be able to convert this to type "unknown" with parser code changes

2. Content issue
Also in references, many of them are converted to `unknown` type automatically if they are missing key attributes that would cause them to fail validation as their type. For example, `bib2` is type `journal` however it is missing something (probably page numbers), so our parser converts it to type `unknown`. The `unknown` reference is not necessarily a problem, except when the reference content is converted, when the reference is convert to a string, the output is messy on the web page. For example, here is what `bib2` looks like:

![image](https://user-images.githubusercontent.com/1779115/57322754-272c8300-70b9-11e9-9e75-12bfa63698eb.png)

I think the `(, ), , . , ` output is due to the content inside `<x>` tags are included when the parser converts it to type `unknown`.

The formatting of references in article `00114` may not be like the others, as @Melissa37 was mentioning today.

@Melissa37 could you please look at these issues concerning the references?

**Comment by gnott** [comment]
Please note there are about a dozen references that display all the extra punctuation, and it is not limited to `bib2`.

**Comment by Melissa37** [comment]
@Vijayarajmurugesan 

I had a look at the XML and noticed:

```
<sec id="s1">
            <label>1.</label>
            <title>Introduction</title>
```

I think this is going to cause problems for the eLife site, and the label should be part of the title:

```<sec id="s1">
            <title>1. Introduction</title>```

Please fix and resupply.

We also noticed that the references suddenly have tags such as `<x>` and `<comment>` (eg: `<comment>Chapter 6</comment>`) which has never been allowed in eLife content.
The punctuation is contained within `<x>` tags, despite `<element-citation>` being used, which means punctuation should not appear in the XML.
The first set of samples we saw, 001 - 003 had good XML structure for the references, but this has disappeared in this last sample. Please check your validation and rules, as this has gone awry. It woudl be good if you can find where this crept in and re-do those from where the switch occurred (and tell us).

Another example is:
`<date-in-citation>[20/2/2015]</date-in-citation>` - this is not the standard tagging for eLfe references!

Yet in another reference this is the tagging:
`<comment>[20/03/2014]</comment>'

' <string-name>
                            <surname>Buddelmeyer</surname>
                            <x> </x>
                            <given-names>Hielke</given-names>
                        </string-name>
`
String names have appeared too.

>Validation issue
bib15 is type <element-citation publication-type="working-paper">, currently the demo site does not support working-paper types, having no template on how to display it. If it is possible please to change this to one of the reference types already supported? If not, I may be able to convert this to type "unknown" with parser code changes

bib15 - please change this to `@publication-type="report"`

>For example, bib2 is type journal however it is missing something (probably page numbers), so our parser converts it to type unknown. The unknown reference is not necessarily a problem, except when the reference content is converted, when the reference is convert to a string, the output is messy on the web page.

```
<ref id="bib2">
                <element-citation publication-type="journal">
                    <person-group person-group-type="author">
                        <string-name>
                            <surname>Brown</surname>
                            <x> </x>
                            <given-names>Laurie</given-names>
                        </string-name>
                        <x>, and </x>
                        <string-name>
                            <surname>Harding</surname>
                            <x> </x>
                            <given-names>Ann</given-names>
                        </string-name>
                    </person-group>
                    <x> (</x>
                    <year iso-8601-date="2002">2002</year>
                    <x>), </x>
                    <article-title>Social Modelling and Public Policy: Application of
                        Microsimulation Modelling in Australia</article-title>
                    <x>. </x>
                    <source>Journal of Artificial Societies and Social Simulation</source>
                    <x> </x>
                    <volume>vol. 5</volume>
                    <x>, no. </x>
                    <issue>4</issue>
                    <x>; </x>
                    <uri xlink:href="http://jasss.soc.surrey.ac.uk/5/4/6.html"
                        >http://jasss.soc.surrey.ac.uk/5/4/6.html</uri>
                </element-citation>
            </ref>
```

Should be changed to:

```
<ref id="bib2">
                <element-citation publication-type="journal">
                    <person-group person-group-type="author">
<name>
                            <surname>Brown</surname>
                            <given-names>Laurie</given-names>
</name>
<name>
                             <surname>Harding</surname>
                             <given-names>Ann</given-names>
</name>
<name>
                    </person-group>
                    <year iso-8601-date="2002">2002</year>
                    <article-title>Social Modelling and Public Policy: Application of
                        Microsimulation Modelling in Australia</article-title>
                    <source>Journal of Artificial Societies and Social Simulation</source>
                    <volume>5</volume>
                    <issue>4</issue>
                    <uri xlink:href="http://jasss.soc.surrey.ac.uk/5/4/6.html"
                        >http://jasss.soc.surrey.ac.uk/5/4/6.html</uri>
                </element-citation>
            </ref>
```
I have looked this up and the page numbers are:  pp. 1-6 - can you add them in and remove the url, which is not working any more anyway.

I appreciate we cannot manually fix all the poor references we find. But let's do it for this one and if we find a few more.
Ref: http://www.canberra.edu.au/researchrepository/items/09789eef-14e0-a5f8-daa5-3f5c08444a19/1/

**Comment by Melissa37** [comment]
@matteorichiardi for info:

Brown Laurie , and Harding Ann ( 2002 ), Social Modelling and Public Policy: Application of Microsimulation Modelling in Australia . Journal of Artificial Societies and Social Simulation vol. 5 , no. 4 ; http://jasss.soc.surrey.ac.uk/5/4/6.html ```

The url does not work any more and the reference is missing the page numbers. I've looked it up and found them, but depending on how many there are, we probably won't be able to do this for all references that do not conform to current eLife "style requirements"

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 

Apologies for the inconvenience, In the kriya XML, containing the x tags, and string-names are included due to punctuations are shown up in the Kriya. In the package, particularly "ijm-00114" created as a kriya XML. Now we have fixed the issue and resupply the package to the below link. I hope everything is fixed this package.

https://exeterpremedia.exavault.com/share/view/1i5dm-9s6a5s81

Thanks,
Vijay

**Comment by Melissa37** [comment]
@Vijayarajmurugesan Many thanks!
I have now created a new column on the board (resupplied). 
Please comment on the issue when it's been resupplied, as you have done, but also move the issue to this new column and re-assign the issue to me, taking yourself off it.

Is that OK?

Thanks!

**Comment by Melissa37** [comment]
@gnott 

 `<ref id="bib9">`

Contains:
`<comment>Also published in Dutch</comment>`

I don't think it will display on Continuum, which is not a big problem. I can see no other way to tag this, so I think it should remain and be a consideration for Libero.

A couple of the bibs contain `<date-in-citation>`not in the eLife format, for example `<date-in-citation>[20/6/2011]</date-in-citation>` in `<ref id="bib12">`. I don't think Exeter should have to change these as they are what's supplied. They have not added an iso value, but I think that is OK too.

I am moving this to resupplied and assigning to you for re-loading.

@thewilkybarkid for info.

**Comment by matteorichiardi** [comment]
The url is working for me!
The Journal of Artificial Societies and Social Simulation is html only and
does not have page numbers, so the correct citation is vol. 5, no. 4, art. 6

Matteo

**Comment by Melissa37** [comment]
Ah OK, thanks @matteorichiardi 

There is no tag available in the DTD for article number or anything that corresponds with that, so suggest you use <elocation-id> @Vijayarajmurugesan 

Please change as below:

```
<ref id="bib2">
                <element-citation publication-type="journal">
                    <person-group person-group-type="author">
<name>
                            <surname>Brown</surname>
                            <given-names>Laurie</given-names>
</name>
<name>
                             <surname>Harding</surname>
                             <given-names>Ann</given-names>
</name>
<name>
                    </person-group>
                    <year iso-8601-date="2002">2002</year>
                    <article-title>Social Modelling and Public Policy: Application of
                        Microsimulation Modelling in Australia</article-title>
                    <source>Journal of Artificial Societies and Social Simulation</source>
                    <volume>5</volume>
                    <issue>4</issue>
<elocation-id>4</elocation-id>
                    <uri xlink:href="http://jasss.soc.surrey.ac.uk/5/4/6.html"
                        >http://jasss.soc.surrey.ac.uk/5/4/6.html</uri>
                </element-citation>
            </ref>
```

**Comment by gnott** [comment]
> `<comment>Also published in Dutch</comment>`
> I don't think it will display on Continuum, which is not a big problem. I can see no other way to tag this, so I think it should remain and be a consideration for Libero.

The reference is currently converted to type of `unknown`, where everything is used to show something, _à la_:

![image](https://user-images.githubusercontent.com/1779115/57414306-6be51680-71ac-11e9-8e0e-4ebee54e2993.png)

If the missing data is added to allow it to be a valid `book` reference, then the comment will I think not be shown.

**Comment by Melissa37** [comment]
@gnott The problem is it is a journal and not a book!
The sample XML given to Exeter has all the required fields for a journal reference so it should work.
Thanks!
M

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 
As your suggestion, we fixed the reference. I have re-uploaded the package for the below link:
https://exeterpremedia.exavault.com/share/view/1i5dm-9s6a5s81
Thanks,
Vijay

**Comment by Melissa37** [comment]
@Vijayarajmurugesan I get this error message and cannot download it:
![Screenshot 2019-05-15 at 15 59 53](https://user-images.githubusercontent.com/6051876/57785939-88dc9500-772a-11e9-83b7-1624494d9946.png)

Also, can you confirm you've made all the changes I requested 8 days ago?

And final question! Are these are still samples at this stage? That is, Matteo has not approved and signed them off for final publication?

Thanks!
M

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 
This is fixed. I have reuploaded the updated package to the below path:

https://exeterpremedia.exavault.com/share/view/1i5dm-9s6a5s81
Regards,
Vijay

**Comment by gnott** [comment]
The resupplied `00114` article is valid, thanks @Vijayarajmurugesan!
