### ISSUE TITLE
XML subject: Retirement e.g.

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#28]
Testing on article `ijm-00003.xml`, an error is raised on the demo journal site when clicking a subject link at the bottom of the article page:

http://localhost:8080/subjects/retirement

The subject `Retirement` was changed to `Pensions and retirement` in issue https://github.com/microsimulation/ijm-xml/issues/18.

If these new subject heading values could be used in the XML files please it will cause fewer errors and I will not have to rewrite the old subject values.

The example in `ijm-00003.xml` of 

```
<subj-group subj-group-type="heading">
<subject>Retirement</subject>
</subj-group>
```

I think would be better as

```
<subj-group subj-group-type="heading">
<subject>Pensions and retirement</subject>
</subj-group>
```

@Melissa37 if you could please confirm we want this, and the values in all XML files must be from the approved subject values.

**Comment by Melissa37** [comment]
@Vijayarajmurugesan please can you fix early samples so they use the updated terms Matteo provided.

Thanks!

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 
I have fixed this issue. Now I have resupplied the articles ijm-00001 to 4, 6 &7 to the below link:
https://exeterpremedia.exavault.com/share/view/1i5dm-9s6a5s81
Thanks,
Vijay

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 
I have fixed this issue and resupplied to the below link:
https://exeterpremedia.exavault.com/share/view/1i5dm-9s6a5s81
Thanks,
Vijay

**Comment by gnott** [comment]
Regarding the subject value of `Retirement`, when searching the most recently supplied XML, I find one article with the value, `ijm-00012.xml`

```
<subject>Retirement</subject>
```

If this one could also please be converted to `<subject>Pensions and retirement</subject>`.

**Comment by Vijayarajmurugesan** [comment]
@gnott I have fixed and reuploaded to the below link:
https://exeterpremedia.exavault.com/share/view/1jbyg-1kd0axsa

Regards,
Vijay

**Comment by gnott** [comment]
Fixes confirmed, thanks @Vijayarajmurugesan!
