### ISSUE TITLE
ijm-00010.xml validation ORCID values

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#29]
Converting `ijm-00010.xml` to JSON and checking for validation, the ORCID values for the authors is not in an accepted format, 

```
<contrib-id contrib-id-type="orcid" authenticated="true">www.arqus.info</contrib-id>
```

**Comment by Melissa37** [comment]
@Vijayarajmurugesan this is a big error here.
For one, it's not an ORCID and secondly, it cannot have the attribute `@authenticated="true"` as the content is not authenticated in any way! If you do have ORCIDs provided in PDFs for IJM then this attribute cannot be added.

Please convert to an author footnote:

Link from author:
` <xref ref-type="fn" rid="fn1"/>`

Footnote:
```
<author-notes>
 <fn fn-type="fn" id="fn1">
<p>www.arqus.info</p>
</fn>
</author-notes>
```

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 Fixed this issue.
https://exeterpremedia.exavault.com/share/view/1i5dm-9s6a5s81

**Comment by Melissa37** [comment]
@Vijayarajmurugesan  - when you cannot do something as we requested can you feedback to us rather than making another decision without consultation please?

@gnott 
I requested the below to be changed to `fn1` 

```
<xref ref-type="fn" rid="fna"/>
    ...
   <author-notes>
    <fn fn-type="fn" id="fna">
     <p>www.arqus.info</p>
    </fn>
```

However, Exeter cannot do this as there is another `fn1` in the document, in the `<back>` in Notes:

```
<back>
  <fn-group>
   <title>Notes</title>
   <fn id="fn1">
    <label>1.</label>
    <p>If microsimulation is indispensable for certain complex research questions and there is a
     lack of tax microdata it might be recommendable to run a microsimulation on the basis of
     synthetic microdata generated from grouped data. These synthetic data could be generated using
     various data bases, for example data from other samples (consumer panel data) or from national
     accounting and merge these data with the grouped data from the tax statistics. users of such
     synthetic microdata have to check whether the generated microdata are representative for the
     underlying research question and taxpayers. In case of analyses on tax revenue effects
     synthetic microdata will usually not be representative. If microdata is not representative, for
     example, because of missing important attributes in the aggregate data base, the results of a
     microsimulation will be wrong. For other research questions this data inaccuracy can be less
     relevant and hence negligible.</p>
   </fn>
   <fn id="fn2">
    <label>2.</label>
    <p>For a continuous-time approach cf., e.g., <xref ref-type="bibr" rid="bib10">Galler
      (1997)</xref>.</p>
   </fn>
...
```

1) Can Continuum handle this, 2) @thewilkybarkid is this the right decision to make for the document structure in Libero?

**Comment by gnott** [comment]
The resupplied XML has the `fn` tag with `id="fna"`. I am testing it on the demo site, and I think it is functioning correctly. The page loads, and the content appears, both in the contributor name pop-up box and in the additional information, which looks like this:

![image](https://user-images.githubusercontent.com/1779115/58320013-926f9800-7dcf-11e9-85c6-7a80ad6f8b06.png)

Is there more you would like to confirm @Melissa37 before this issue is closed?

**Comment by Melissa37** [comment]
I think we can close this for now. @thewilkybarkid can address this issue for Libero and I think Libero will need to be flexibile enough to allow for this sort of thing too.
Thanks G!
M
