### ISSUE TITLE
No corresponding author

### ISSUE THREAD

**Issue by Melissa37** [microsimulation/ijm-xml#3]
IJM content does not have a corresponding author.
Check Libero can cope with this scenario as eLife journal always has corresp author

**Comment by gnott** [comment]
I think this may be based on the presence of `emailAddresses` for a particular author. There may not be a specific value in the article JSON to specify which author is the corresponding one. The corresponding author(s) my be implied by the presence of `emailAddresses`.

**Comment by Melissa37** [comment]
Exeter made a mistake yesterday and suddenly they were delivering all email addresses even for non corresponding authors. They showed up in Continuum. This is good as it meant we could identify this error. As our XML goes elsewhere and we don't check it when hosted elsewhere (eg PMC), this was great. I think this covers this scenario? The only difference with IJM is that nobody is designated the corresponding author and whether the JSON validator fails the article for not having a corresponding author identified in the XML?

M

**Comment by gnott** [comment]
I checked journal JSON schema, Crossref generation, and PubMed generation, and none of those use the corresponding attribute of an author (as far as I could tell). I'm not sure about PMC and how they use the XML for that purpose. So far it seems to be valid and little impact to not indicate which author(s) are corresponding authors.

**Comment by Melissa37** [comment]
So I can move this to the fixed column and close the issue?

**Comment by gnott** [comment]
Fixed and closed seems ok to me too!
