### ISSUE TITLE
ijm-00016 empty table

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#31]
The JSON produced from XML file `ijm-00016.xml` is valid according to the schema (I think).

When viewing article `00016` there is a new exception:

```
Value "<ARRAY>" is empty, but non empty value was expected.
```

which is associated with

```
Assertion::notEmpty($tables);
```

Looking for tables, there is only Table 1. In the XML I think it is a table in a TIF file, here

```
<table-wrap id="table1" position="float">
<label>Table 1</label>
<caption>
<title>Example Policy Parameter Sheet</title>
</caption>
<graphic xlink:href="ijm-00016-tab1.tif" mimetype="image" mime-subtype="tiff"/>
</table-wrap>
```

@Melissa37 I don't think we can support a TIF in a `<table-wrap>` tag. I think it might be solved if it goes into a `<fig>` tag, but it can retain the `<label>Table 1</label>`. I'm not too sure, but it's an idea to solve the validation problem.

**Comment by Melissa37** [comment]
@Vijayarajmurugesan in the PDF file the table is editable. 

Please format it as a table in the XML - it has been converted to an image by the conversion processing.
The colour grey should be ignored for the XML version.

**Comment by Vijayarajmurugesan** [comment]
@gnott This  is fixed

**Comment by gnott** [comment]
Thanks @Vijayarajmurugesan, I am viewing a table now.
