### ISSUE TITLE
ijm-00004.xml person-group tag

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#32]
I am rechecking earlier files after removing the code hack to allow plain `<person-group>` tags to work.

Converting the `ijm-00004.xml` file I have fails now due to the `<person-group>` tags.

@Melissa37 if you could please check and comment or assign this for resupply?

**Comment by Melissa37** [comment]
@Vijayarajmurugesan we'll need a resupply I am afraid.

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 
I have fixed this issue and resupplied to the below link:
https://exeterpremedia.exavault.com/share/view/1i5dm-9s6a5s81
Thanks,
Vijay

**Comment by gnott** [comment]
Resupply `<person-group>` tag fixes look ok. When working with the file I noticed it is possibly invalid XML, the closing tag in `bib8` seems to be the problem:

```
<version>version 1.0.4<version>
```

I think should be `</version>` at the end.

@Melissa37 could you please comment and suggest whether a resupply is in order?

**Comment by Vijayarajmurugesan** [comment]
@gnott @Melissa37 
I have fixed this issue. Now you can access the correct version of the package to the below link:

**Comment by gnott** [comment]
The resupplied package XML is valid now, thanks Vijay!
