### ISSUE TITLE
ijm-00008.xml person-group tag

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#33]
`<person-group>` is present in the references and I cannot convert these with no `person-group-type` attribute.

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 
This is fixed. Please find the updated files by below path:
https://exeterpremedia.exavault.com/share/view/1i5dm-9s6a5s81
Thanks,
Vijay

**Comment by Melissa37** [comment]
Thanks!

**Comment by gnott** [comment]
The XML for article `00008` has compatible `<person-group>` tags, thanks Vijay!
