### ISSUE TITLE
ijm-00043.xml bib21 reference

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#43]
A validation issue arises after converting this XML to JSON:

```
<ref id="bib21"><element-citation publication-type="web"><person-group><collab>OECD</collab></person-group><year iso-8601-date="2008">2008</year><source>A Profile of Immigrant Populations in the 21st Century</source><publisher-loc>Paris</publisher-loc><publisher-name>OECD</publisher-name></element-citation></ref>
```

The JSON schema requires it to have a `uri`, and there is no URI / URL in the reference.

Please note issue https://github.com/microsimulation/ijm-xml/issues/40 also concerns the `ijm-00043.xml` file.

**Comment by Melissa37** [comment]
@Vijayarajmurugesan Please convert to a book ref

**Comment by Vijayarajmurugesan** [comment]
@Melissa37
Fixed the issue and uploaded the package to an ftp site:
https://exeterpremedia.exavault.com/share/view/1i5dm-9s6a5s81
Regards,
Vijay

**Comment by gnott** [comment]
Book reference is converting and valid, thanks Vijay.
