### ISSUE TITLE
ijm-00044.xml confproc references

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#44]
References of type `confproc` in XML file `ijm-00044.xml` when converted to JSON the resutl is not valid against the schema.

These references are:

```
bib7
bib8
bib13
```

One solution is to add an `<article-title>` tag to the references, which will populate the `articleTitle` attribute in the JSON file. Alternatively, one code fix (if `<source>` tag is preferred) is I need to change our XML parser to use that value as the `articleTitle` when `<article-title>` is not present.

Please note, there is a similar issue about references of type `confproc` in issue https://github.com/microsimulation/ijm-xml/issues/24

**Comment by Melissa37** [comment]
@Vijayarajmurugesan 

Bib7

 ```
<ref id="bib7">
                <element-citation publication-type="confproc">
                    <collab>Eurostat</collab>
                    <year iso-8601-date="2004">2004</year>
                    <source>Income in EU-SILC: Net-Gross-Net Conversion; Common Structure of the
                        Model; Model Description; and Application to ECHP Data for France, Italy and
                        Spain</source>
                    <conf-name>EU-SILC 133/04, Working Group on Statistics on Income and Living
                        Conditions (EU-SILC)</conf-name>
                    <conf-date>29&#x2013;30 March 2004</conf-date>
                    <conf-loc>Luxembourg</conf-loc>
                    <conf-sponsor>Eurostat</conf-sponsor>
                </element-citation>
            </ref>
```

Please change:
```
<source>Income in EU-SILC: Net-Gross-Net Conversion; Common Structure of the
                        Model; Model Description; and Application to ECHP Data for France, Italy and
                        Spain</source>
```

To:
```
<article-title>Income in EU-SILC: Net-Gross-Net Conversion; Common Structure of the
                        Model; Model Description; and Application to ECHP Data for France, Italy and
                        Spain</article-title>
```

Please add:
`<year>2004</year>`

**Comment by Melissa37** [comment]
@gnott I assume it's Ok to leave '<conf-date>29&#x2013;30 March 2004</conf-date>' as it's semantically correct although we will not display it on Continuum - we should retain for Libero

**Comment by gnott** [comment]
> @gnott I assume it's Ok to leave '29–30 March 2004' as it's semantically correct although we will not display it on Continuum - we should retain for Libero

`<conf-date>29&#x2013;30 March 2004</conf-date>` does not end up in the JSON or on the demo site and will not cause any issues 👍

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 
Fixed the issue and uploaded the package to an ftp site:
https://exeterpremedia.exavault.com/share/view/1i5dm-9s6a5s81
Regards,
Vijay

**Comment by gnott** [comment]
In terms of validation, the references identified here in the feedback for resupply are valid and improved.

There's another part causing a validation issue, in `bib9`:

```
<element-citation publication-type="reprot">
```

This will convert properly if this is `"report"` rather than `"reprot"`. This may be clear enough for resupply without Melissa checking? Thanks Vijay!

**Comment by Vijayarajmurugesan** [comment]
@gnott 
Fixed the issue and uploaded the package to an ftp site:
https://exeterpremedia.exavault.com/share/view/1jbyg-1kd0axsa
Regards,
Vijay

**Comment by gnott** [comment]
There are no errors in validating or showing this article on the demo site (I didn't look too carefully at the actual content). Thanks @Vijayarajmurugesan!
