### ISSUE TITLE
Figure image quality or resolution

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#46]
I don't know if the figure TIF files are out of scope for the XML conversion project. I wanted to add this observation of image quality at this time, since I might be the only one viewing articles right now.

E.g. article 00035 fig 4.

A screen capture when I view the PDF file, at a reasonable size but slightly larger dimension than the TIF in the zip package:

![image](https://user-images.githubusercontent.com/1779115/57404748-9aa1c380-7191-11e9-813f-aaad07a6cddd.png)

Screen shot when I view the TIF from the article zip package (keeping some grey borders so the smaller dimension is somewhat visible when Github resizes the image too be larger than it really is):

![image](https://user-images.githubusercontent.com/1779115/57404927-0edc6700-7192-11e9-804c-4616b77f4e3e.png)

How it looks on a demo site page:

![image](https://user-images.githubusercontent.com/1779115/57404976-2b789f00-7192-11e9-9943-ed7f3fb58538.png)

If you would care to please comment @Melissa37 about the image quality or resolution.

**Comment by Melissa37** [comment]
@gnott this is out of scope for eLife, but one for @matteorichiardi and @Vijayarajmurugesan to discuss.

I'll leave it in the backlog until we hear back from IJM or Exeter.
Thanks for pointing this out though!
