### ISSUE TITLE
incorrect iso date values

### ISSUE THREAD

**Issue by Melissa37** [microsimulation/ijm-xml#47]
Hi @Vijayarajmurugesan 

Here is a message from Graham:

>I did a first conversion of 00034 to 00054 (in the May 2 folder) to check for major validation issues.
All are reported, except there are some incorrect iso date values. 

Please can you check all your content before doing resupplies. I assume this is "a" and "b" being added to the iso date value instead of the display date only

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 
This is fixed. I have checked and replace correct iso date values.
Regards,
Vijay

**Comment by Melissa37** [comment]
thanks

**Comment by gnott** [comment]
I am going through the article resupply issues and evaluating them against the content resupplied so far. I noticed a reference iso date with a non-numeric character in it. I drafted a quick regular expression search to find some in this format:

```
iso-8601-date="[0-9][0-9][0-9][0-9][a-z]">
```

Searching over the most recent XML articles these are the date values I found (my apologies if any are from previous versions, however I think most of these are from the most recent resupplied XML):

00003
bib3
bib4

00016 (according to the most recent file I have)
bib7
bib8
bib15

00020
bib7
bib8

00021
bib7

00022
bib3
bib4

00023
bib14
bib15
bib23
bib24

00028
bib4
bib5

When these values are non-numeric, on the demo site the date will not be displayed, however I think the more important aspect is for the XML quality itself especially when it is used in the future.

@Melissa37 if you could please review my comments and specify the next actions, unless it is clear that resupplies are needed for these articles again please @Vijayarajmurugesan.

**Comment by Melissa37** [comment]
@Vijayarajmurugesan they will need resupplies, sorry!

**Comment by Vijayarajmurugesan** [comment]
@gnott I fixed all the issues. Now I have uploaded the updated files to the below link:

https://exeterpremedia.exavault.com/share/view/1jbyg-1kd0axsa

Thanks,
Vijay

**Comment by gnott** [comment]
All the non-numeric iso date values are fixed in my search on the resupplied articles, thanks @Vijayarajmurugesan!
