### ISSUE TITLE
Micro-macro links / linkage subject

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#50]
Adding more content, I noticed the subject used in some XML files:

```
<subject>Micro-macro linkage</subject>
```

We have this in the demo site as:

```
Micro-macro links
```

This mismatch will raise an exception if you try to view the subject link http://localhost:8080/subjects/micro-macro-linkage

@Melissa37 could you please confirm which wording is correct: in the XML, or the subject name in the demo site?

**Comment by Melissa37** [comment]
@Vijayarajmurugesan 

we are working from the list Matteo sent:
https://docs.google.com/spreadsheets/d/1NVrM0u8mokZGrRa5aHr9YOfnL0jy0h49HyAaXzlUn_Y/edit#gid=1910847622 on the topics list page
But I see that when IJM filled in the Topics on the articles tab they did not use the same terms.

@matteorichiardi This one is for you.

Can you confirm which it should be used and also cross check the terms used in both places to ensure they match?

Thanks!

**Comment by matteorichiardi** [comment]
I confirm that the list on the spreadsheet is the one to be used. I have
double checked it and removed a couple of inconsistencies between the list
and the info reported in the articles sheet. I hope no other
inconsistencies remain, but if you find them please give priority to the
list.
Thanks,
Matteo

**Comment by Melissa37** [comment]
Great, thanks @matteorichiardi 

Over to you @Vijayarajmurugesan

**Comment by gnott** [comment]
In this case, `<subject>Micro-macro linkage</subject>` looks to be correct, so I will update the subject name in the demo site.

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 
This is fixed. I have updated all the issues.
Regards,
Vijay

**Comment by Melissa37** [comment]
thanks

**Comment by gnott** [comment]
I think all the occurrences of the old subject value are fixed in the articles supplied so far, thanks Vijay!
