### ISSUE TITLE
Wrong pub dates 1-40, inclusive

### ISSUE THREAD

**Issue by Melissa37** [microsimulation/ijm-xml#51]
I am previewing content received so far, which I'm adding to the demo project. I created issues for the dates above for articles to be associated with.

Unfortunately, the issue dates do not match the article pub dates for all articles from 00001 to 00040, inclusive. These may all need to be resupplied with new pub dates.

Articles 00041 to 00054 pub dates are correct!

@Vijayarajmurugesan please resupply

**Comment by gnott** [comment]
From the most recent batch of resupply articles, I reviewed the pub dates in the XML. From articles up to `00054`, there is only one where I found potentially an incorrect pub date.

In `ijm-00004.xml`, I think it needs to be updated to `2007-12-31`.

If you could please confirm and consider for resupply of this pub date value?

**Comment by Melissa37** [comment]
@Vijayarajmurugesan please can you correct and resupply ijm-00004.xml

**Comment by Vijayarajmurugesan** [comment]
@gnott I fixed this issue. Please find the below link for updated files:
https://exeterpremedia.exavault.com/share/view/1jbyg-1kd0axsa
Thanks,
Vijay

**Comment by gnott** [comment]
Date is correct on the final article, thanks @Vijayarajmurugesan.
