### ISSUE TITLE
 publicID in the XML file's doctype is incorrect 

### ISSUE THREAD

**Issue by Melissa37** [microsimulation/ijm-xml#52]
The publicID in the XML file's doctype is incorrect - it should be

`-//NLM//DTD JATS (Z39.96) Journal Archiving and Interchange DTD v1.2 20190208//EN`

rather than

`-//NLM//DTD JATS (Z39.96) Journal Archiving and Interchange DTD v1.2 20151215//EN`

This is eLife's fault, sorry. We need to update it for eLife too. The reason I found out is because it fails on the JATS4R validator tool:

https://validator.jats4r.org/

Can you update it for all articles?

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 I will fix this and resupply it one by one.

**Comment by gnott** [comment]
Almost all of the resupplied articles so far do not have the `20151215` value when I search through them, except for the XML in zip package `ijm-00052-vor-r2.zip`. Maybe you would like to evaluate the conditions for completion on the issue @Melissa37, whether you'd like me to run a find operation on all the XML when everything is complete? Or you could consider the issue resolved.

**Comment by Melissa37** [comment]
I consider this resolved, thanks G and also to @Vijayarajmurugesan for fixing it!
M
