### ISSUE TITLE
ijm-00053 Conversion issue

### ISSUE THREAD

**Issue by Melissa37** [microsimulation/ijm-xml#54]
Link to https://github.com/microsimulation/ijm-xml/issues/49

>I have noticed that the numbered sections have been split between <label> and <title> again. Please can you move the labels into the titles?
`<sec id="s1">`
            `<title>1. Introduction</title>`

Here is a screenshot of how this does not work on Continuum site:
![Screenshot 2019-05-17 at 14 52 55](https://user-images.githubusercontent.com/6051876/57932934-e819e100-78b3-11e9-9b71-8d020407ac8d.png)

The label does not show, and cross links in text to the section number are confusing as the section names are missing from the section titles and

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 This is fixed
