### ISSUE TITLE
ijm-0018: error in conversion of section title

### ISSUE THREAD

**Issue by Melissa37** [microsimulation/ijm-xml#59]
Conversion of section title
![Screenshot 2019-05-17 at 15 17 08](https://user-images.githubusercontent.com/6051876/57934156-eb629c00-78b6-11e9-9795-a89e518d468c.png)

APPLICATIONS OF Health&WealthMOD in PDF turned into:
`title>Applications of health&#x0026;wealth mod</title>`

Health&WealthMOD is the way this is displayed in every other place, it's a term.

**Comment by Vijayarajmurugesan** [comment]
@Melissa37 
This is fixed. Please see the updated files by below path
https://exeterpremedia.exavault.com/share/view/1i5dm-9s6a5s81
Thanks,
Vijay

**Comment by gnott** [comment]
The title value looks good in the most recently supplied XML file, thanks Vijay!
