### ISSUE TITLE
Open citations: Papers and Citeulike don't work 

### ISSUE THREAD

**Issue by Melissa37** [microsimulation/ijm-xml#62]
Nothing happens if you click on Papers
![Screenshot 2019-05-17 at 15 28 21](https://user-images.githubusercontent.com/6051876/57934926-8b6cf500-78b8-11e9-8410-bb3e0d0d73bc.png)

This is what happens for Citeulike:
![Screenshot 2019-05-17 at 15 29 29](https://user-images.githubusercontent.com/6051876/57934947-99bb1100-78b8-11e9-8572-06dc3fe2f5b9.png)

**Comment by BlueReZZ** [comment]
The Libero MVP which IJM will use is only planned to have a single download button for the PDF so these should probably be removed/hidden otherwise they may expect the same on launch.

**Comment by Melissa37** [comment]
Thanks @BlueReZZ - who can do this? Who should this be assigned to?

**Comment by BlueReZZ** [comment]
I can probably do it with some assistance from @giorgiosironi as it seems to be a case of removing a some lines here:

https://github.com/microsimulation/demo/blob/6c060a9aa600ea420c86f39bc786483da4b7fb36/journal/src/ViewModel/Converter/ArticleDownloadLinksListConverter.php#L55

**Comment by BlueReZZ** [comment]
This has been done under PR https://github.com/microsimulation/demo/pull/11 and merged. Just waiting for @giorgiosironi to deploy it
