### ISSUE TITLE
ijm-00051.xml bib7 validation issue

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#63]
The most recent resupplied package for IJM article `00051` reported an error when validating the JSON output from the XML file.

I believe the reason is due to reference id `bib7`, having the following:

```
<element-citation publication-type="Report">
```

The conversion process works better when the type is lowercase `"report"`.

If you would please consider to change this and resupply @Vijayarajmurugesan? I am bypassing Melissa's check to save time in this case, since it seems to be such a simple change.

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed.

**Comment by gnott** [comment]
No validation issues remain, thanks @Vijayarajmurugesan!
