### ISSUE TITLE
ijm-00075.xml conversion and validation issues

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#64]
Starting on the next batch of content, article `00075` is the first one to not produce output due to error.

1. Errors in conversion

In the reference list the XML has `<mixed-citation>` tags, and it will be more compatible if these were all changed to `<element-citation>` please @Vijayarajmurugesan 

2. Errors in validation

I checked for potential validation issues, and these are possibly all the issues in my quick test:

2a. DOI prefix is `10.XXXXX`, could you please change it to the correct prefix?

2b. There are some empty subject tags which cause validation issues. If these could be populated with values or the empty ones removed please?

```
<subj-group subj-group-type="heading">
<subject/>
</subj-group>
```

2c. Section `s5-1` does not have a `<title>`, and I think we require a title for each section to consider it to be valid.

If you could please consider these element for resupply of article `00075` please @Vijayarajmurugesan  -- thank-you!

**Comment by Vijayarajmurugesan** [comment]
@gnott This fixed and reuploaded.

**Comment by gnott** [comment]
This article converted and validated correctly, thanks @Vijayarajmurugesan
