### ISSUE TITLE
00076, 00077, 00078, 00079, 00080

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#65]
Similar to issue https://github.com/microsimulation/ijm-xml/issues/64, these articles -- `00076`, `00077`, `00078`, `00079`, and `00080` -- have at least three things which are causing conversion and validation problems for me:

1. Errors in conversion

In the reference list the XML has `<mixed-citation>` tags, and it will be more compatible if these were all changed to `<element-citation>` please @Vijayarajmurugesan 

2. Errors in validation

I checked for potential validation issues, and these are possibly all the issues in my quick test:

2a. DOI prefix is `10.XXXXX`, could you please change it to the correct prefix?

2b. There are some empty subject tags which cause validation issues. If these could be populated with values or the empty ones removed please?

```
<subj-group subj-group-type="heading">
<subject/>
</subj-group>
```

If you could please resupply these five articles @Vijayarajmurugesan - thanks!

**Comment by gnott** [comment]
Added the detail about blank subject tags, also apply here, would have been omitted from any email notification. All the issues known so far are in the original comment - thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed.

**Comment by gnott** [comment]
Regarding the parts identified above in these articles, they are fixed - thanks @Vijayarajmurugesan!
