### ISSUE TITLE
00082, 00083, 00084, 00099, 00100, 00101, 00102

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#66]
These seven articles - `00082`, `00083`, `00084`, `00099`, `00100`, `00101`, and `00102` - I have an error in converting them to JSON due to at least one error:

In the reference list the XML has `<mixed-citation>` tags, and it will be more compatible if these were all changed to `<element-citation>`.

Thanks @Vijayarajmurugesan!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed.

**Comment by gnott** [comment]
These article converted with no problems so it looks fixed, thanks @Vijayarajmurugesan!
