### ISSUE TITLE
ijm-00061.xml abstract

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#67]
I have a validation issue in the abstract of article `00061`. In the XML it has `<sec>` tags, and I am guessing it was produced in a structured abstract format.

The abstract in the PDF looks like this:

![image](https://user-images.githubusercontent.com/1779115/58486920-9d9e2d00-811b-11e9-90c7-45e5aa9a56fc.png)

I think the quickest and easiest change to make the XML valid would be to put all the abstract text into one `<p>` tag. I think for the demo site that is all that can be supported.

I do not know what the near-term support for structured abstracts are on the roadmap, so I'd like to mention @Melissa37 and @thewilkybarkid on this issue.

If you have time @Melissa37 you can please comment on whether the single paragraph abstract will work here. If no comment from Melissa, could you please format the abstract for this article into the one `<p>` tag so we can show it on the demo? If not, we cannot show it (which might be ok too, but it would depend on when structured abstract support is planned to be added).

**Comment by Melissa37** [comment]
>I think the quickest and easiest change to make the XML valid would be to put all the abstract text into one <p> tag. I think for the demo site that is all that can be supported.

I agree - for the Libero site we need to support.

@matteorichiardi FYI

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed

**Comment by gnott** [comment]
For the purposes of the demo site, article `00061` in its present form is able to display now. It also allows me to add the collection for the issue where this article appears. Thanks @Vijayarajmurugesan!

@Melissa37 I'm not completely sure about any further instructions - are you suggesting for after the demo site, the abstract should be changed back to have `<sec>` tags for later Libero support? I will assign this ticket back to you for a final review please.

**Comment by Melissa37** [comment]
Thanks both for getting this loaded. I would have preferred to keep the sec tagging for the final content, but as the work's been done to change it back that's fine.

If Matteo wants it changed for the final version then he can raise it as an issue on the spreadsheet.

Thanks!
