### ISSUE TITLE
ijm-00069.xml reference type

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#70]
A validation error in the reference list, 

```
<element-citation publication-type="jounal">
```

If you could please change `jounal` to `journal` type @Vijayarajmurugesan - thank-you!

**Comment by gnott** [comment]
This is on `bib23` I think.

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed

**Comment by gnott** [comment]
Confirmed, fixed and valid, thanks @Vijayarajmurugesan!
