### ISSUE TITLE
ijm-00070.xml bib7 reference type

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#71]
An issue with validating the output from article `00070`, reference id `bib7` is:

```
<element-citation publication-type="reprot">
```

Could you please change `"reprot"` to `"report"` @Vijayarajmurugesan? Thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed

**Comment by gnott** [comment]
Valid on the demo site, thanks @Vijayarajmurugesan!
