### ISSUE TITLE
ijm-00071.xml bib4 bib7 type

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#72]
A couple references on `ijm-00071.xml` are causing validation issues, having:

```
<element-citation publication-type="reprot">
```

If you could change the `"reprot"` to `"report"` on these please @Vijayarajmurugesan - thank-you!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed

**Comment by gnott** [comment]
Confirmed fixed, thanks @Vijayarajmurugesan
