### ISSUE TITLE
ijm-00074.xml DOI prefix and subjects

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#73]
A validation issue with article `ijm-00074.xml` due to the DOI prefix value, and I think there are also some blank subject tags. @Vijayarajmurugesan could you please change these in the XML and resupply? Thank-you!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed now.

**Comment by gnott** [comment]
Is showing on the demo site under Editorial subject, thanks @Vijayarajmurugesan!
