### ISSUE TITLE
ijm-00086.xml display channel and institution

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#74]
A couple validation issues with article `00086`.

First is if you could please add this for the article type support to make it valid,

```
<subj-group subj-group-type="display-channel">
<subject>Research article</subject>
</subj-group>
```

Second, the author does not have an `<institution>` tag and value. If it is possible to find and add a value for this, it is the quickest way for the demo site to display the article. If it is not possible to add an institution I will have to look at bypassing the validation for this item, since it seems to be coming up on more than one article.

Thanks @Vijayarajmurugesan!

**Comment by Vijayarajmurugesan** [comment]
@gnott This issue fixed and uploaded to the ftp site.

Thanks,
Vijay

**Comment by gnott** [comment]
This looks ok here too, thanks @Vijayarajmurugesan!
