### ISSUE TITLE
ijm-00088.xml display channel and institution

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#76]
Similar to issues raised recently, if you could please add

```
<subj-group subj-group-type="display-channel">
<subject>Research article</subject>
</subj-group>
```

to the XML.

There is also an author with no `<institution>` tag, which I hope you can populate with something?

Thanks @Vijayarajmurugesan

**Comment by gnott** [comment]
I notice article `00088` in the XML may specify it being in volume 5, issue 1, however I think this article may supposed to be in volume 6, issue 3. If you could please check and alter this in the resupply if that is true, thanks @Vijayarajmurugesan.

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed.

**Comment by gnott** [comment]
All looks right, thanks @Vijayarajmurugesan!
