### ISSUE TITLE
ijm-00089.xml display channel and image file name

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#77]
Testing validation on article `00089`, I have found two changes that would help with validating the output.

1. Display channel - if you could please add:

```
<subj-group subj-group-type="display-channel">
<subject>Research article</subject>
</subj-group>
```

2. Image file name

The image cannot be found in order to populate the dimensions. I think if you change `xlink:href="ijm00089-fig1.tif"` to `xlink:href="ijm-00089-fig1.tif"` then the file name will match the file in the zip package.

Could you make these changes to `00089` please @Vijayarajmurugesan? Thank-you!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed.

**Comment by gnott** [comment]
The parts above are valid now I think, thanks @Vijayarajmurugesan!
