### ISSUE TITLE
ijm-00091.xml sec title

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#79]
In `00091` there is one `<sec>` tag, but it is invalid against the demo site rules because it has no `<title>` tag. Is there something that could be used here for the time being @Vijayarajmurugesan?

I will flag this one for @Melissa37 too, because I guess it really shouldn't have any title there, and is something that should maybe not be changed in the XML, and this should just remain invalid and not shown on the demo site?

**Comment by Melissa37** [comment]
@matteorichiardi would you be happy to provide a single heading title for this article?
It's fine if you don't want to and will be a good test case for Libero rules, but we won't be able to host it on the demo site without one!

![Screenshot 2019-05-28 at 21 47 55](https://user-images.githubusercontent.com/6051876/58511228-4a1af600-8192-11e9-9468-a6a5274b6190.png)

Thanks
Melissa

**Comment by matteorichiardi** [comment]
Heading should be 'Editorial'. The remaining part of the title ('Spatial
microsimulation') should be the title of the special issue. I discussed
with Chris the possibility to give titles to issues, he explained me that
issues are identified by a string not a number so every labelling is
possible...
I hope I understood correctly.
Matteo

**Comment by Melissa37** [comment]
Ah sorry, no worries. I realise my mistake and this is for @Vijayarajmurugesan 

@Vijayarajmurugesan please remove the `<sec>` so it is like eLife content - an example of an editorial is 36263

```</front>
    <body>
        <p>Before eLife published its first article, there was already strong agreement within the
            ...
```

**Comment by gnott** [comment]
Good catch @Melissa37! When I test with the `<sec>` tag removed I think the output is valid. Looking forward to the resupply, thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott  I have fixed this and re-uploaded the updated package to the below email.
https://exeterpremedia.exavault.com/share/view/1jbyg-1kd0axsa

Thanks,
Vijay

**Comment by gnott** [comment]
Thanks for the `Main text` title, it can be shown on the demo site now, thanks @Vijayarajmurugesan!
