### ISSUE TITLE
ijm-00092.xml bib27 type

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#80]
One reference type to change please should make this article XML valid.

Please change `bib27`

```
<element-citation publication-type="conf-proc">
```

type from `"conf-proc"` to `"confproc"`.

Thanks @Vijayarajmurugesan!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed.

**Comment by gnott** [comment]
Article is valid, thanks @Vijayarajmurugesan!
