### ISSUE TITLE
ijm-00094.xml bib1 reference

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#81]
In validating the JSON output for article `00094`, there is one reference causing a problem, `bib1`. I think the reason is the `<pub-id pub-id-type="doi">1351.0.55.006</pub-id>` value does not match the accepted format for a DOI. @Vijayarajmurugesan, could you please alter this value or move it to a tag that is not for a DOI?

@Melissa37 may have a thought what can go here regarding content (if time allows for comment).

**Comment by Melissa37** [comment]
This is not a DOI, it's an ABS Catalogue no attached to the title:

1351.0.55.006 - Research Paper: Small Area Estimation of Disability in Australia, Oct 2005  

https://www.abs.gov.au/ausstats/abs@.nsf/mf/1351.0.55.006

```
<ref id="bib1">
                <element-citation publication-type="book">
                    <person-group person-group-type="author">
                        <collab>ABS</collab>
                    </person-group>
                    <year iso-8601-date="2005">2005</year>
                    <source>Small area estimates of Disability in Australia</source>
                    <publisher-loc>Canberra</publisher-loc>
                    <publisher-name>ABS</publisher-name>
                    <pub-id pub-id-type="doi">1351.0.55.006</pub-id>
                </element-citation>
```

Suggest change to:

```
<ref id="bib1">
                <element-citation publication-type="journal">
                    <person-group person-group-type="author">
                        <collab>ABS</collab>
                    </person-group>
                    <year iso-8601-date="2005">2005</year>
<article-title>Small area estimates of Disability in Australia</article-title>
                    <source>ABS</source>
                    <elocation-id>1351.0.55.006</pub-id>
                </element-citation>
```

**Comment by Vijayarajmurugesan** [comment]
@gnott I have fixed as Melissa suggested. Now I have uploaded the resupply package to the ftp path.

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed and resupplied

**Comment by gnott** [comment]
I think this is fixed @Vijayarajmurugesan, thanks! However there's another ref issue I think, for which I'll open a new ticket.
