### ISSUE TITLE
ijm-00097.xml sec title

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#82]
There is a small technical issue with XML for article `00097` causing a validation issue, and I would like to suggest a change please.

```
<sec id="s7a">
<label>Annex 1</label>
```

If the label tag is changed to a title tag, to this:

```
<sec id="s7a">
<title>Annex 1</title>
```

then it is easier for me to validate.

@Vijayarajmurugesan would you be able to change to this please? Thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott Now this is fixed. Please check now.

**Comment by gnott** [comment]
The output is valid now, thanks @Vijayarajmurugesan!
