### ISSUE TITLE
ijm-00107.xml display channel and image file names

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#84]
Testing XML for article `00107`, I found two parts in the package I think will need to be part of a resupply:

1. XML display channel

If you could please add to the article XML,

```
<subj-group subj-group-type="display-channel">
<subject>Research article</subject>
</subj-group>
```

2. Image file names

Some file names in the zip package do not match the names in the XML, such as these:

```
ijm-00108-ufig1.tif
ijm-00108-ufig2.tif
ijm-00108-ufig3.tif
ijm-00108-ufig4.tif
ijm-00108-ufig5.tif
ijm-00108-ufig6.tif
```

If the file names are changed from `00108` to `00107` the names would match what is in the XML, otherwise we have trouble populating the image dimensions from the IIIF image server.

If you could please change the article XML as described above and resupply the article, thank-you @Vijayarajmurugesan!

**Comment by Vijayarajmurugesan** [comment]
@gnott I have fixed this issue and resupplied.

**Comment by gnott** [comment]
No errors in converting this article, thanks @Vijayarajmurugesan!
