### ISSUE TITLE
ijm-00108.xml author affiliation

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#85]
There is one part of the XML for article `00108` which causes a validation error.

The author does not have an `<institution>` tag and value. If it is possible to add one, then the article can be displayed on the demo site. If not, this article may be counted in the list of articles that will not display at this time.

If you are able to add an institution @Vijayarajmurugesan, it would be helpful. If you cannot add one, we can probably move this issue to the "will not fix" column, or wait for more input from Melissa and others.

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed and resupplied

**Comment by gnott** [comment]
This article is working too, thanks @Vijayarajmurugesan!
