### ISSUE TITLE
Article 00105 has it been supplied?

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#89]
Hi @Vijayarajmurugesan, I'm assembling more complete issues. I cannot find article `00105` anywhere yet, and have you supplied it already at some point? I think this would be in Volume 7 Issue 3, entitled `The MicSim Package of R: An Entry-Level Toolkit for Continuous-Time Microsimulation`.

Thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott I have uploaded the article ijm-00105 to the below ftp site:

https://exeterpremedia.exavault.com/share/view/1jfw0-7kmixv2r

Thanks,
Vijay

**Comment by gnott** [comment]
Package received, thanks for resending it @Vijayarajmurugesan. I have a new issue regarding it out to Melissa (https://github.com/microsimulation/ijm-xml/issues/100) but I can close this particular issue.
