### ISSUE TITLE
00125 to 00132 file names

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#90]
Dear @Vijayarajmurugesan,'

In reviewing the new packages in the range of articles `00125` to `00132`, I notice the zip file name has a dot where all the others have a hyphen, e.g. `ijm.00125-vor-r1.zip`. The `ijm.00125` would be better as `ijm-00125` please. I think the XML and PDF file names inside the zip file follow the dot pattern as well, and would require changing to hyphens.

I can change the file names locally to continue reviewing so as to not hold up the process.

Thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott Sorry for the inconvenience caused. Now am fixed this issue and uploaded the updated files to the ftp site:
https://exeterpremedia.exavault.com/share/view/1jfw0-7kmixv2r

**Comment by gnott** [comment]
I had no problems with file names on these in the latest batch, thanks again @Vijayarajmurugesan.
