### ISSUE TITLE
ijm-00129.xml bib4 and bib31

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#91]
Two references in article `00129` produced some validation errors. I think these are because the references of type `"report"` have an `<article-title>` tag instead of using a `<source>` tag. Since other references of type `report` are using the `<source>` tag, I think it would be right to use `<source>` throughout. If you agree and would be able to resupply this article please @Vijayarajmurugesan it would be much appreciated!

**Comment by Vijayarajmurugesan** [comment]
@gnott I have fixed this issue and re-uploaded to the below link:

https://exeterpremedia.exavault.com/share/view/1jfw0-7kmixv2r

Thanks,
Vijay

**Comment by gnott** [comment]
I think article `00129` is valid now, thanks @Vijayarajmurugesan!
