### ISSUE TITLE
00163 to 00167 file names

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#94]
Similar to issue https://github.com/microsimulation/ijm-xml/issues/90, I am reviewing the latest list of article content (thanks!) and I see some zip files with these names:

```
ijm.00163-vor-r1.zip
ijm.00164-vor-r1.zip
ijm.00165-vor-r1.zip
ijm.00166-vor-r1.zip
ijm.00167-vor-r1.zip
```

@Vijayarajmurugesan, could you please review these and resupply with `ijm.` changed to `ijm-` on the zip files, and also on any `.xml` or `.pdf` (or other files) inside these zip files.

Thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott I have fixed the file naming issues and resupplied the packages to the below ftp site:

https://exeterpremedia.exavault.com/share/view/1jm6r-6kjkpwlw

Regards,
Vijay

**Comment by gnott** [comment]
Zip file names are repaired, thanks @Vijayarajmurugesan!
