### ISSUE TITLE
00181 file name ijm-00181-fig6 .tif

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#95]
I am using the semi-automated scripts I have to process the zip for `00181`. There's a file name `ijm-00181-fig6 .tif` in the zip file (with a whitespace character before the `.tif` extension). This name doesn't match with the value in the XML file, which will become a problem when showing the figure.

@Vijayarajmurugesan, could you please rename this file to `ijm-00181-fig6.tif` and resupply the zip? Thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott I have fixed the figure naming issue and resupplied the package to the below ftp site:
https://exeterpremedia.exavault.com/share/view/1jm6r-6kjkpwlw

Thanks,
Vijay


Regards,
Vijay

**Comment by gnott** [comment]
Regarding the latest zip package for article `00181`, the file name identified has changed, however, the figure file names in the XML do not match the files themselves. These have a `.` where they should have a `-`:

```
<graphic xlink:href="ijm.00181-fig1.tif" mimetype="image" mime-subtype="tiff"/>
<graphic xlink:href="ijm.00181-fig2.tif" mimetype="image" mime-subtype="tiff"/>
<graphic xlink:href="ijm.00181-fig3.tif" mimetype="image" mime-subtype="tiff"/>
<graphic xlink:href="ijm.00181-fig4.tif" mimetype="image" mime-subtype="tiff"/>
<graphic xlink:href="ijm.00181-fig5.tif" mimetype="image" mime-subtype="tiff"/>
<graphic xlink:href="ijm.00181-fig6.tif" mimetype="image" mime-subtype="tiff"/>
<graphic xlink:href="ijm.00181-fig7.tif" mimetype="image" mime-subtype="tiff"/>
<graphic xlink:href="ijm.00181-fig8.tif" mimetype="image" mime-subtype="tiff"/>
<graphic xlink:href="ijm.00181-fig9.tif" mimetype="image" mime-subtype="tiff"/>
<graphic xlink:href="ijm.00181-fig10.tif" mimetype="image" mime-subtype="tiff"/>
<graphic xlink:href="ijm.00181-figC1.tif" mimetype="image" mime-subtype="tiff"/>
<graphic xlink:href="ijm.00181-figC2.tif" mimetype="image" mime-subtype="tiff"/>
<graphic xlink:href="ijm.00181-figG1.tif" mimetype="image" mime-subtype="tiff"/>
```

Would you please update the XML for this article and resupply it again please @Vijayarajmurugesan - thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott This is fixed. I have uploaded the resupply package to the below ftp path:
https://exeterpremedia.exavault.com/share/view/1jmpq-42nt8dul
Regards,
Vijay
