### ISSUE TITLE
PDF files with dot . instead of hyphen -

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#96]
In addition to the zip files with a `.` in the file name, I've noticed some PDF and XML files that are inside the zip files with a `.` instead of a `-`:

```
ijm.00125.pdf
ijm.00126.pdf
ijm.00127.pdf
ijm.00128.pdf
ijm.00129.pdf
ijm.00130.pdf
ijm.00131.pdf
ijm.00132.pdf
ijm.00168.pdf
ijm.00169.pdf
ijm.00170.pdf
ijm.00171.pdf
ijm.00192.pdf
```

@Vijayarajmurugesan could you please review these packages and file names, and rename `'ijm.` to `ijm-` on the PDF files? Thanks!

**Comment by Vijayarajmurugesan** [comment]
@gnott The articles ijm-00125 to ijm-00132 looks fine only in our zip file. For your reference please find the below link to access the articles: https://exeterpremedia.exavault.com/share/view/1jfw0-7kmixv2r 
If you have any issues, please let me know. 

For other articles, I have fixed the issues and resupplied ot the below link:
https://exeterpremedia.exavault.com/share/view/1jm6r-6kjkpwlw

Thanks,
Vijay

**Comment by gnott** [comment]
Thanks for checking on these Vijay. I think the PDF files with a `.` were some noise from my attempts to unzip the zip files with a `.` in the name. I removed them from my folders for a clean start.
