### ISSUE TITLE
XML files with dot . instead of hyphen -

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#97]
Similar to the PDF files names with a `.` instead of a `-` character, there are some XML files I am seeing with similar names:

```
ijm.00163.xml
ijm.00164.xml
ijm.00165.xml
ijm.00166.xml
ijm.00167.xml
ijm.00168.xml
ijm.00169.xml
ijm.00170.xml
ijm.00171.xml
```

Could you please check on these @Vijayarajmurugesan in the zip packages supplied, and if you see a `ijm.` change it to `ijm-`? Thank-you!

**Comment by Vijayarajmurugesan** [comment]
@gnott I have fixed the file naming issues and resupplied the packages to the below ftp site:

https://exeterpremedia.exavault.com/share/view/1jm6r-6kjkpwlw

Regards,
Vijay

**Comment by gnott** [comment]
The file name `.` characters look good, thanks @Vijayarajmurugesan. Articles `00167`, `00170`, and `00171` I cannot produce output yet, but these are covered in open issues for resupply at this time.
