### ISSUE TITLE
ijm-00114.xml XML issues

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm-xml#99]
Initially I ran into trouble converting the XML for article `00114`, due to the empty content in

```
<article-id pub-id-type="publisher-id"></article-id>
```

Would you please change this to

```
<article-id pub-id-type="publisher-id">00114</article-id>
```

There is also a validation issue and content issue in the XML:

Please add:

```
<subj-group subj-group-type="display-channel">
<subject>Editorial</subject>
</subj-group>
```

Also, could you please change

```
<self-uri content-type="pdf" xlink:href="ijm.00114.pdf"/>
```
 
to

```
<self-uri content-type="pdf" xlink:href="ijm-00114.pdf"/>
```

(file name change to use hyphen instead of a dot).

I'll be checking for `<self-uri>` values throughout all the articles later. I don't think any incorrect file names there would show on the demo site since the PDF file name is generated from the article ID.

Thanks @Vijayarajmurugesan!

**Comment by Vijayarajmurugesan** [comment]
@gnott I have fixed the above issue and resupplied the package to the below ftp site:

https://exeterpremedia.exavault.com/share/view/1jm6r-6kjkpwlw

Regards,
Vijay

**Comment by gnott** [comment]
These parts are updated, and the output is valid now, thanks @Vijayarajmurugesan!
